### ISSUE TITLE
Add "Can't Reproduce" status

### ISSUE THREAD

**Issue by claus** [MadeInHaus/QA#2]
Add "Can't Reproduce" to Ticket Statuses? It's fairly common and i never know what to pick when this comes up.

**Comment by stevescavo** [comment]
This is essentially the infamous `Works For Me` status - which we don't currently have. @kevin-madeinhaus you have any thoughts? IMO `Can't Reproduce` is a nicer way of saying "works for me". I say we add it.

**Comment by stevescavo** [comment]
@claus @kevin-madeinhaus added via e5e2984ac2d0a2614d585d321c6fba1705602b2c. Let's add it to our Codebase project templates.
